runtime: nodejs18 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "tempconvert-382312.appspot.com"

handlers:
- url: /stylesheets
  static_dir: public/stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
